spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "4.0"

accounts:
  message: "Welcome to EazyBank loans related Production APIs "
  contactDetails:
    name: "Tapajyoti Ghosh - Production Lead"
    email: "tghosh@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345