spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Arya Mitra - QA Lead"
    email: "amitra@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345